# Travis-CI Configuration
language: python

matrix:
  include:
    - python: "3.5"
      dist: precise
    - python: "3.6"
      dist: trusty
    - python: "3.7"
      dist: xenial

install:
  - pip install -r requirements.txt
  - pip install -e .

before_script: cd tests

script:
  - pytest
