# Travis-CI Configuration
language: python

python:
  - 3.5
  - 3.6

matrix:
  include:
    - python: "3.7"
      dist: xenial

install:
  - pip install -r requirements.txt
  - pip install -e .

before_script: cd tests

script:
  - pytest
