# Project information
site_name: 'ISCC - Content Identifiers'
site_description: 'International Standard Content Code - Specification'
site_author: 'Titusz Pan'
site_url: 'http://iscc.codes'

# Repository
repo_name: 'coblo/iscc-specs'
repo_url: 'https://github.com/coblo/iscc-specs'
edit_uri: 'edit/master/docs/'

# Copyright
copyright: 'Copyright © 2016-2018 Content Blockchain Project'

# Documentation and Theme
theme:
    name: 'material'
    language: 'en'
    logo: 'images/logo-white.svg'
    favicon: 'images/favicon.png'
    palette:
        primary: 'blue'
        accent: 'pink'
    feature:
        tabs: false

extra_css:
  - 'stylesheets/custom.css'

nav:
    - Overview: 'index.md'
    - Concept: 'concept.md'
    - Specification: 'specification.md'
    - Implementations: 'implementations.md'
    - License: 'license.md'

# Options
extra:
    search:
        language: 'en'
    social:
        - type: 'home'
          link: 'https://content-blockchain.org'
        - type: 'github'
          link: 'https://github.com/coblo'
        - type: 'telegram'
          link: 'https://t.me/ContentBlockchainBeta'


markdown_extensions:
    - markdown.extensions.abbr
    - markdown.extensions.admonition
    - markdown.extensions.codehilite:
        linenums: false
        guess_lang: false
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
        permalink: '#'
    - pymdownx.magiclink
